import { AcademyLesson } from '../types';

export const ACADEMY_LESSONS: AcademyLesson[] = [
    {
        id: 'wallets_storage',
        title: 'What are Crypto Wallets — Explained for Beginners',
        category: 'wallets',
        level: 'beginner',
        provider: 'binance',
        videoId: 'd8IBpfs9bf4',
        youtubeUrl: 'https://www.youtube.com/watch?v=d8IBpfs9bf4',
        officialArticleUrl: 'https://academy.binance.com/uk/articles/crypto-wallet-types-explained',
        fallbackUrl: 'https://academy.binance.com/uk/articles/crypto-wallet-types-explained',
        spokenLanguage: 'en',
        subtitleLanguages: ['uk', 'en'],
        duration: '5:12',
        thumbnailUrl: 'https://img.youtube.com/vi/d8IBpfs9bf4/hqdefault.jpg',
        sourceVerifiedAt: '2026-09-28',
        embedStatus: 'verified',
        disclaimer: 'Офіційний освітній матеріал Binance Academy. Не є фінансовою порадою.'
    },
    {
        id: 'cryptocurrency_basics',
        title: 'What is Cryptocurrency — Explained for Beginners',
        category: 'basics',
        level: 'beginner',
        provider: 'binance',
        videoId: 'a5XfQWUUZM8',
        youtubeUrl: 'https://www.youtube.com/watch?v=a5XfQWUUZM8',
        officialArticleUrl: 'https://academy.binance.com/uk/articles/what-is-cryptocurrency',
        fallbackUrl: 'https://academy.binance.com/uk/articles/what-is-cryptocurrency',
        spokenLanguage: 'en',
        subtitleLanguages: ['uk', 'en'],
        duration: '4:45',
        thumbnailUrl: 'https://img.youtube.com/vi/a5XfQWUUZM8/hqdefault.jpg',
        sourceVerifiedAt: '2026-09-28',
        embedStatus: 'verified',
        disclaimer: 'Офіційний освітній матеріал Binance Academy. Не є фінансовою порадою.'
    },
    {
        id: 'blockchain_basics',
        title: 'How Does Blockchain Work — Explained for Beginners',
        category: 'basics',
        level: 'beginner',
        provider: 'binance',
        videoId: '3rL0OIXbMio',
        youtubeUrl: 'https://www.youtube.com/watch?v=3rL0OIXbMio',
        officialArticleUrl: 'https://academy.binance.com/uk/articles/what-is-blockchain-and-how-does-it-work',
        fallbackUrl: 'https://academy.binance.com/uk/articles/what-is-blockchain-and-how-does-it-work',
        spokenLanguage: 'en',
        subtitleLanguages: ['uk', 'en'],
        duration: '5:42',
        thumbnailUrl: 'https://img.youtube.com/vi/3rL0OIXbMio/hqdefault.jpg',
        sourceVerifiedAt: '2026-09-28',
        embedStatus: 'verified',
        disclaimer: 'Офіційний освітній матеріал Binance Academy. Не є фінансовою порадою.'
    },
    {
        id: 'bitcoin_intro',
        title: 'What is Bitcoin — Explained for Beginners',
        category: 'basics',
        level: 'beginner',
        provider: 'binance',
        videoId: 'Wnf2vKG90w8',
        youtubeUrl: 'https://www.youtube.com/watch?v=Wnf2vKG90w8',
        officialArticleUrl: 'https://academy.binance.com/uk/articles/what-is-bitcoin',
        fallbackUrl: 'https://academy.binance.com/uk/articles/what-is-bitcoin',
        spokenLanguage: 'en',
        subtitleLanguages: ['uk', 'en'],
        duration: '6:15',
        thumbnailUrl: 'https://img.youtube.com/vi/Wnf2vKG90w8/hqdefault.jpg',
        sourceVerifiedAt: '2026-09-28',
        embedStatus: 'verified',
        disclaimer: 'Офіційний освітній матеріал Binance Academy. Не є фінансовою порадою.'
    },
    {
        id: 'mining_intro',
        title: 'What is Cryptocurrency Mining — Explained for Beginners',
        category: 'basics',
        level: 'beginner',
        provider: 'binance',
        videoId: '2VtH-XAOjXw',
        youtubeUrl: 'https://www.youtube.com/watch?v=2VtH-XAOjXw',
        officialArticleUrl: 'https://academy.binance.com/uk/articles/what-is-crypto-mining-and-how-does-it-work',
        fallbackUrl: 'https://academy.binance.com/uk/articles/what-is-crypto-mining-and-how-does-it-work',
        spokenLanguage: 'en',
        subtitleLanguages: ['uk', 'en'],
        duration: '5:30',
        thumbnailUrl: 'https://img.youtube.com/vi/2VtH-XAOjXw/hqdefault.jpg',
        sourceVerifiedAt: '2026-09-28',
        embedStatus: 'verified',
        disclaimer: 'Офіційний освітній матеріал Binance Academy. Не є фінансовою порадою.'
    },
    {
        id: 'trading_fundamentals',
        title: 'Online Course for Beginners: Trading Fundamentals',
        category: 'trading',
        level: 'beginner',
        provider: 'binance',
        videoId: 'URZuENfa8tI',
        youtubeUrl: 'https://www.youtube.com/watch?v=URZuENfa8tI',
        officialArticleUrl: 'https://academy.binance.com/uk/articles/a-complete-guide-to-cryptocurrency-trading-for-beginners',
        fallbackUrl: 'https://academy.binance.com/uk/articles/a-complete-guide-to-cryptocurrency-trading-for-beginners',
        spokenLanguage: 'en',
        subtitleLanguages: ['uk', 'en'],
        duration: '7:40',
        thumbnailUrl: 'https://img.youtube.com/vi/URZuENfa8tI/hqdefault.jpg',
        sourceVerifiedAt: '2026-09-28',
        embedStatus: 'verified',
        disclaimer: 'Офіційний освітній курс Binance Academy. Не є фінансовою порадою.'
    },
    {
        id: 'trading_strategies',
        title: 'Online Course for Beginners: Trading Strategies',
        category: 'trading',
        level: 'intermediate',
        provider: 'binance',
        videoId: 'YqoJ_fOHoH8',
        youtubeUrl: 'https://www.youtube.com/watch?v=YqoJ_fOHoH8',
        officialArticleUrl: 'https://academy.binance.com/uk/articles/trading-strategies-for-beginners',
        fallbackUrl: 'https://academy.binance.com/uk/articles/trading-strategies-for-beginners',
        spokenLanguage: 'en',
        subtitleLanguages: ['uk', 'en'],
        duration: '8:15',
        thumbnailUrl: 'https://img.youtube.com/vi/YqoJ_fOHoH8/hqdefault.jpg',
        sourceVerifiedAt: '2026-09-28',
        embedStatus: 'verified',
        disclaimer: 'Офіційний освітній курс Binance Academy. Не є фінансовою порадою.'
    },
    {
        id: 'bnb_vault_guide',
        title: 'What is BNB Vault & How to Use It — Official Guide',
        category: 'basics',
        level: 'beginner',
        provider: 'binance',
        videoId: 'STFXi-FNzJM',
        youtubeUrl: 'https://www.youtube.com/watch?v=STFXi-FNzJM',
        officialArticleUrl: 'https://academy.binance.com/uk',
        fallbackUrl: 'https://academy.binance.com/uk',
        spokenLanguage: 'en',
        subtitleLanguages: ['uk', 'en'],
        duration: '4:10',
        thumbnailUrl: 'https://img.youtube.com/vi/STFXi-FNzJM/hqdefault.jpg',
        sourceVerifiedAt: '2026-09-28',
        embedStatus: 'verified',
        disclaimer: 'Офіційний посібник Binance. Не є фінансовою рекомендацією.'
    },
    {
        id: 'bybit_wallets',
        title: 'Bybit Learn: What is a Crypto Wallet and How Does it Work?',
        category: 'wallets',
        level: 'beginner',
        provider: 'bybit',
        officialArticleUrl: 'https://learn.bybit.com/crypto/what-is-a-crypto-wallet/',
        fallbackUrl: 'https://learn.bybit.com/crypto/what-is-a-crypto-wallet/',
        spokenLanguage: 'en',
        subtitleLanguages: ['en'],
        duration: '6 хв читання',
        sourceVerifiedAt: '2026-09-28',
        embedStatus: 'verified',
        disclaimer: 'Офіційна навчальна стаття Bybit Learn.'
    },
    {
        id: 'okx_security',
        title: 'OKX Learn: How to Secure Your Crypto Assets & Self-Custody',
        category: 'security',
        level: 'intermediate',
        provider: 'okx',
        officialArticleUrl: 'https://www.okx.com/en-us/learn/tag/security',
        fallbackUrl: 'https://www.okx.com/en-us/learn/tag/security',
        spokenLanguage: 'en',
        subtitleLanguages: ['en'],
        duration: '5 хв читання',
        sourceVerifiedAt: '2026-09-28',
        embedStatus: 'verified',
        disclaimer: 'Офіційні матеріали з безпеки та самостійного зберігання OKX Learn.'
    },
    {
        id: 'okx_wallets',
        title: 'OKX Learn: Complete Guide to Non-Custodial Web3 Wallets',
        category: 'wallets',
        level: 'beginner',
        provider: 'okx',
        officialArticleUrl: 'https://www.okx.com/en-us/learn/tag/wallets',
        fallbackUrl: 'https://www.okx.com/en-us/learn/tag/wallets',
        spokenLanguage: 'en',
        subtitleLanguages: ['en'],
        duration: '7 хв читання',
        sourceVerifiedAt: '2026-09-28',
        embedStatus: 'verified',
        disclaimer: 'Офіційні матеріали про Web3-гаманці від OKX Learn.'
    }
];

export const ACADEMY_LESSONS_MAP = new Map(ACADEMY_LESSONS.map(l => [l.id, l]));
