import { AcademyTerm, Language } from '../types';

export const ACADEMY_DATABASE: Record<Language, AcademyTerm[]> = {
    en: [
        // ==========================================
        // 1. PATTERNS & SMC (CHART STRUCTURE & CANDLES)
        // ==========================================
        { id: 'hns', term: 'Head & Shoulders', category: 'PATTERNS', definition: 'A classic reversal pattern with three peaks (left, head, right). Break of the neckline confirms shift from Bullish to Bearish.', visualType: 'CHART_HEAD_SHOULDERS', example: 'Price failed at $72k, broke neckline at $65k.' },
        { id: 'bullflag', term: 'Bull Flag', category: 'PATTERNS', definition: 'A bullish continuation pattern. A steep impulsive rise (pole) followed by a tight downward-sloping channel (flag).', visualType: 'CHART_BULL_FLAG', example: 'Consolidation after +15% impulse, breakout upward.' },
        { id: 'fallingwedge', term: 'Falling Wedge', category: 'PATTERNS', definition: 'Bullish reversal or continuation pattern where price consolidates lower with converging support and resistance lines.', visualType: 'CHART_WEDGE_BULL', example: 'Divergence at lower trendline precedes upside surge.' },
        { id: 'risingwedge', term: 'Rising Wedge', category: 'PATTERNS', definition: 'Bearish pattern with higher highs and higher lows converging into an apex. Signals buying exhaustion.', visualType: 'CHART_WEDGE_BEAR', example: 'Volume fades as price grinds up into breakdown.' },
        { id: 'doji', term: 'Doji Candle', category: 'PATTERNS', definition: 'Candlestick where open and close prices are virtually identical. Indicates complete equilibrium and indecision between bulls and bears.', visualType: 'CANDLE_DOJI', example: 'Doji at local resistance warns of reversal.' },
        { id: 'hammer', term: 'Bullish Hammer', category: 'PATTERNS', definition: 'Bullish reversal candle with a tiny upper body and a long lower wick (at least 2x body), rejecting lower prices.', visualType: 'CANDLE_HAMMER', example: 'Pin-bar bounce off major support.' },
        { id: 'engulfing', term: 'Bullish Engulfing', category: 'PATTERNS', definition: 'Two-candle reversal where a large green candle body completely overtakes and closes above the prior red candle body.', visualType: 'CANDLE_ENGULFING', example: 'Buyers overpower sellers at daily range low.' },
        { id: 'morningstar', term: 'Morning Star', category: 'PATTERNS', definition: 'A 3-candle bottom reversal: large red candle, small indecision star candle, followed by strong green candle closing above midpoint.', visualType: 'CANDLE_MORNING_STAR', example: 'Bottom confirmed on the 4H timeframe.' },
        { id: 'shootingstar', term: 'Shooting Star', category: 'PATTERNS', definition: 'Bearish reversal candle with a small lower body and a long upper wick, showing aggressive seller rejection at highs.', visualType: 'CANDLE_SHOOTING_STAR', example: 'Failed breakout leaves long wick, leads to drop.' },
        { id: 'cupandhandle', term: 'Cup & Handle', category: 'PATTERNS', definition: 'Bullish continuation structure. A rounded accumulation bottom (cup) followed by a slight downward drift (handle) before expansion.', visualType: 'CHART_CUP_HANDLE', example: 'Long-term accumulation breaking all-time high.' },
        { id: 'doubletop', term: 'Double Top ("M")', category: 'PATTERNS', definition: 'Bearish reversal pattern. Price hits the same resistance level twice, fails to break, and drops below the interim swing low.', visualType: 'CHART_DOUBLE_TOP', example: 'Exhaustion at $70,000 double rejection.' },
        { id: 'doublebottom', term: 'Double Bottom ("W")', category: 'PATTERNS', definition: 'Bullish reversal pattern. Price tests key support twice, creates a higher low or equal low, and breaks the neckline upward.', visualType: 'CHART_DOUBLE_BOTTOM', example: 'Support defense at $60,000 bounce.' },
        { id: 'ascendingtriangle', term: 'Ascending Triangle', category: 'PATTERNS', definition: 'Bullish formation with horizontal upper resistance and ascending higher lows, demonstrating progressive buying pressure.', visualType: 'CHART_ASC_TRIANGLE', example: 'Buyers pressing against $100 ceiling until breakout.' },
        { id: 'descendingtriangle', term: 'Descending Triangle', category: 'PATTERNS', definition: 'Bearish formation with flat support and descending lower highs, signaling heavy institutional selling pressure.', visualType: 'CHART_DESC_TRIANGLE', example: 'Support repeatedly retested until it snaps.' },
        { id: 'smc', term: 'Smart Money Concepts (SMC)', category: 'PATTERNS', definition: 'Trading framework focused on institutional order flow, tracking where market makers generate liquidity before real moves.', visualType: 'CHART_SMC', example: 'Liquidity sweep of retail stop losses before true pump.' },
        { id: 'orderblock', term: 'Order Block (OB)', category: 'PATTERNS', definition: 'The last opposite-colored candle before an explosive market move that breaks structure, where institutional limit orders remain unfilled.', visualType: 'CHART_OB', example: 'Price retested 4H Bullish OB at $62,400 for entry.' },
        { id: 'fvg', term: 'Fair Value Gap (FVG)', category: 'PATTERNS', definition: 'A 3-candle price imbalance where candle 1 wick and candle 3 wick do not overlap, creating a vacuum that price often revisits.', visualType: 'CHART_FVG', example: 'Limit order placed at 50% FVG (Consequent Encroachment).' },
        { id: 'bos', term: 'BOS (Break of Structure)', category: 'PATTERNS', definition: 'When price makes a clean candle close beyond the prior swing high (in uptrend) or swing low (in downtrend), confirming trend continuation.', visualType: 'CHART_SMC', example: 'Bullish BOS created with a 4H candle body close.' },
        { id: 'choch', term: 'CHoCH (Change of Character)', category: 'PATTERNS', definition: 'The very first structural break of the opposing swing point, indicating potential reversal from bearish to bullish (or vice versa).', visualType: 'CHART_SMC', example: 'CHoCH signaled early bottom before macro trend reversed.' },
        { id: 'liquiditysweep', term: 'Liquidity Sweep (BSL / SSL)', category: 'PATTERNS', definition: 'A quick wick above Equal Highs (BSL) or below Equal Lows (SSL) to hunt stop losses and activate breakout orders before reversing.', visualType: 'CHART_SMC', example: 'Sweep of Asian session high, followed by aggressive drop.' },
        { id: 'breakerblock', term: 'Breaker Block', category: 'PATTERNS', definition: 'A failed Order Block that was violated during a liquidity sweep. When price returns, the broken block flips into powerful opposing support/resistance.', visualType: 'CHART_OB', example: 'Bearish order block broken; now tested as bullish breaker.' },

        // ==========================================
        // 2. TECHNICAL INDICATORS & MARKET MECHANICS
        // ==========================================
        { id: 'rsi', term: 'RSI (Relative Strength Index)', category: 'TECHNICAL', definition: 'Oscillator (0-100) measuring momentum speed. Readings >70 denote overbought conditions; <30 indicate oversold territory.', example: 'Bullish RSI divergence: lower price low with higher RSI low.', visualType: 'NONE' },
        { id: 'macd', term: 'MACD (Moving Average Convergence Divergence)', category: 'TECHNICAL', definition: 'Trend-following momentum indicator displaying the relationship between two EMAs (typically 12 and 26). Crosses signal momentum shifts.', example: 'MACD Golden Cross above zero line confirms bull run.', visualType: 'NONE' },
        { id: 'bollinger', term: 'Bollinger Bands', category: 'TECHNICAL', definition: 'Volatility envelopes set 2 standard deviations above and below a 20-period SMA. Tight band squeezes anticipate volatile explosive breakouts.', example: 'Band squeeze on 1D chart led to a +25% breakout.', visualType: 'NONE' },
        { id: 'fibonacci', term: 'Fibonacci Retracement (Golden Pocket)', category: 'TECHNICAL', definition: 'Horizontal ratio levels based on the golden spiral. The 0.618 - 0.65 zone ("Golden Pocket") is the highest probability reversal zone in a trend.', example: 'Long entry precisely at the 0.618 retracement level.', visualType: 'NONE' },
        { id: 'ema', term: 'EMA 200 & EMA 50 (Death / Golden Cross)', category: 'TECHNICAL', definition: 'Exponential Moving Averages weighting recent prices. EMA 50 crossing above EMA 200 is a "Golden Cross"; crossing below is a "Death Cross".', example: 'Price holding above 200 EMA keeps long-term bull trend intact.', visualType: 'NONE' },
        { id: 'volume', term: 'Volume Profile & POC (Point of Control)', category: 'TECHNICAL', definition: 'Displays volume traded at specific price levels rather than over time. The POC is the single price level with the highest traded volume.', example: 'POC retest acted as impenetrable support during correction.', visualType: 'NONE' },
        { id: 'fundingrate', term: 'Funding Rate (Perpetual Futures)', category: 'TECHNICAL', definition: 'Periodic payments between long and short traders to anchor perp prices to spot. High positive rates (>0.05%) mean longs pay shorts, signaling overheating.', example: 'Extreme negative funding preceded massive short squeeze.', visualType: 'NONE' },
        { id: 'openinterest', term: 'Open Interest (OI)', category: 'TECHNICAL', definition: 'Total number of active, outstanding derivative contracts that have not been settled. Rising price + rising OI = genuine aggressive trend.', example: 'Price dropped with falling OI = simple long liquidation, not new shorting.', visualType: 'NONE' },
        { id: 'cvd', term: 'CVD (Cumulative Volume Delta)', category: 'TECHNICAL', definition: 'Measures net difference between market buy volume and market sell volume. Divergence with price reveals aggressive absorption by limit orders.', example: 'Bullish CVD divergence: Price made equal low while CVD formed higher high.', visualType: 'NONE' },
        { id: 'liqheatmap', term: 'Liquidation Heatmap', category: 'TECHNICAL', definition: 'Visual heat map highlighting price clusters where retail traders leverage stop-outs and forced liquidations sit. Prices act like magnets toward these zones.', example: 'Price wicked up into the $68k liquidation cluster before dropping.', visualType: 'NONE' },
        { id: 'orderbookdepth', term: 'Order Book Depth & Spoofing', category: 'TECHNICAL', definition: 'Bid/Ask depth showing resting limit orders. Spoofing is a manipulative practice of placing large fake orders and canceling before execution.', example: 'Fake 500 BTC bid wall pulled just as price reached it.', visualType: 'NONE' },

        // ==========================================
        // 3. PSYCHOLOGY, RISK MANAGEMENT & SIZING
        // ==========================================
        { id: 'riskreward', term: 'Risk-to-Reward Ratio (R:R)', category: 'PSYCHOLOGY', definition: 'Mathematical relationship between prospective loss and prospective gain. With 1:3 R:R, you can be wrong 60% of the time and still remain profitable.', example: 'Risk $100 to make $300 (1:3 R:R setup).', visualType: 'NONE' },
        { id: 'onepercentrule', term: 'The 1% Rule (Position Sizing)', category: 'PSYCHOLOGY', definition: 'Never risk more than 1% to 2% of your total capital on a single trade idea. Position size = (Account * 1%) / Stop Loss distance.', example: '$10,000 account risks max $100 per invalidation.', visualType: 'NONE' },
        { id: 'fomo', term: 'FOMO (Fear Of Missing Out)', category: 'PSYCHOLOGY', definition: 'The emotional impulse to buy an asset after it has already pumped violently, driven by greed and social envy. Most retail money is lost here.', example: 'Buying a meme token after a 300% green candle.', visualType: 'NONE' },
        { id: 'fud', term: 'FUD (Fear, Uncertainty, Doubt)', category: 'PSYCHOLOGY', definition: 'Negative or misleading information coordinated to depress market sentiment and induce panic selling so institutions can buy cheaply.', example: 'Selling on recycled ban rumors only to watch price rebound.', visualType: 'NONE' },
        { id: 'revengetrading', term: 'Revenge Trading', category: 'PSYCHOLOGY', definition: 'Trading immediately after a painful loss with oversized leverage to recover losses quickly. The #1 cause of complete account blowouts.', example: 'Doubled position size on tilt after getting stopped out.', visualType: 'NONE' },
        { id: 'dca', term: 'DCA (Dollar-Cost Averaging)', category: 'PSYCHOLOGY', definition: 'Investing a fixed dollar amount at regular time intervals regardless of price, removing emotional market timing and volatility stress.', example: 'Allocating $50 into BTC every Monday automatically.', visualType: 'NONE' },
        { id: 'diamondhands', term: 'Diamond Hands vs Paper Hands', category: 'PSYCHOLOGY', definition: '"Diamond Hands" maintain high-conviction positions through drawdowns; "Paper Hands" panic sell at the first minor red candle.', example: 'HODLing spot bags through -30% market shakeouts.', visualType: 'NONE' },
        { id: 'biasconfirmation', term: 'Confirmation Bias & Sunken Cost', category: 'PSYCHOLOGY', definition: 'Seeking only opinions that confirm your losing trade while ignoring technical breakdown. Professional traders cut losers dispassionately.', example: 'Refusing to close invalid trade hoping for a miracle bounce.', visualType: 'NONE' },

        // ==========================================
        // 4. SECURITY, SCAM PROTECTION & ON-CHAIN
        // ==========================================
        { id: 'seed', term: 'Seed Phrase (Secret Recovery Phrase)', category: 'SECURITY', definition: 'A 12 or 24-word master key that derives all private keys. Anyone with this phrase possesses absolute, irreversible control of your funds.', example: 'Store offline on stainless steel; NEVER enter online.', visualType: 'NONE' },
        { id: '2fa', term: '2FA (Two-Factor Authentication)', category: 'SECURITY', definition: 'Time-based one-time password (TOTP) security layer. Always use hardware keys (YubiKey) or Google/Apple Authenticator—never SMS 2FA.', example: 'SMS swap vector prevented by using hardware authenticator.', visualType: 'NONE' },
        { id: 'coldstorage', term: 'Cold Storage (Hardware Wallets)', category: 'SECURITY', definition: 'Specialized hardware keeping private keys in a secure enclave, completely isolated from internet-connected devices (e.g., Ledger, Trezor, Keystone).', example: 'Keeping 90% of long-term crypto assets in cold storage.', visualType: 'NONE' },
        { id: 'drainers', term: 'Drainers & Permit Signatures', category: 'SECURITY', definition: 'Malicious scripts that exploit gasless ERC-20 permit/setApprovalForAll signatures. One blind click grants the attacker permission to empty your wallet.', example: 'Revoke permissions immediately via revoke.cash.', visualType: 'NONE' },
        { id: 'addresspoisoning', term: 'Address Poisoning', category: 'SECURITY', definition: 'Scammers generate vanity addresses with identical first and last 4 characters and send tiny zero-value transactions, hoping you copy from history.', example: 'Always verify full address characters, never copy from history.', visualType: 'NONE' },
        { id: 'honeypot', term: 'Honeypot & 100% Tax Tokens', category: 'SECURITY', definition: 'A fraudulent smart contract that allows you to buy but contains code blocking the `sell()` function, effectively trapping 100% of your funds.', example: 'Checked DexScreener & Honeypot.is before buying new token.', visualType: 'NONE' },
        { id: 'slippage', term: 'Slippage Tolerance & MEV Sandwiches', category: 'SECURITY', definition: 'The difference between expected trade price and execution price. Setting slippage too high (>2%) invites MEV bots to frontrun and sandwich your DEX swap.', example: 'Used private RPC (Flashbots) and 0.5% tight slippage.', visualType: 'NONE' },
        { id: 'fdv', term: 'Market Cap vs FDV (Fully Diluted Valuation)', category: 'SECURITY', definition: 'Circulating Market Cap = Current tokens * Price. FDV = Total max supply * Price. High FDV with low circulation creates brutal token unlock dumps.', example: 'Token had $100M cap but $5B FDV; dumped 80% on unlocks.', visualType: 'NONE' },
        { id: 'smartcontract', term: 'Smart Contract Audit & Admin Keys', category: 'SECURITY', definition: 'Code vulnerabilities or centralized owner keys (upgradeability, mint functions) that allow creators to rug pull or freeze tokens.', example: 'Contract had an unrenounced mint() backdoor.', visualType: 'NONE' },
    ],

    ua: [
        // ==========================================
        // 1. ПАТЕРНИ ТА СТРУКТУРА SMC
        // ==========================================
        { id: 'hns', term: 'Голова і Плечі', category: 'PATTERNS', definition: 'Класичний патерн розвороту з трьома вершинами (ліве плече, голова, праве плече). Пробиття лінії шиї вниз підтверджує перехід до ведмежого тренду.', visualType: 'CHART_HEAD_SHOULDERS', example: 'Ціна не змогла оновити максимум і пробила шию на $65k.' },
        { id: 'bullflag', term: 'Бичачий Прапор', category: 'PATTERNS', definition: 'Патерн продовження бичачого тренду. Складається з різкого імпульсу вгору (флагшток) та короткої низхідної корекції (полотно прапора).', visualType: 'CHART_BULL_FLAG', example: 'Консолідація після +15% росту завершилася імпульсом вгору.' },
        { id: 'fallingwedge', term: 'Падаючий Клин', category: 'PATTERNS', definition: 'Бичачий розворотний патерн. Ціна знижується у звуженому діапазоні між двома лініями, що сходяться. Сигналізує про виснаження продавців.', visualType: 'CHART_WEDGE_BULL', example: 'Бичача дивергенція на клині призвела до пробою вгору.' },
        { id: 'risingwedge', term: 'Зростаючий Клин', category: 'PATTERNS', definition: 'Ведмежий розворотний патерн. Ціна росте, але верхи й низи звужуються, а обсяги падають. Передвіщає різкий спад.', visualType: 'CHART_WEDGE_BEAR', example: 'Згасання обсягів на зростанні спричинило пробій підтримки.' },
        { id: 'doji', term: 'Свічка Доджі', category: 'PATTERNS', definition: 'Свічка, де ціни відкриття та закриття майже ідентичні. Означає абсолютну нерішучість та рівновагу сил між биками та ведмедями.', visualType: 'CANDLE_DOJI', example: 'Доджі на піку денного графіку попередив про розворот.' },
        { id: 'hammer', term: 'Бичачий Молот (Hammer)', category: 'PATTERNS', definition: 'Розворотна свічка з маленьким тілом угорі та довгим нижнім ґнотом (удвічі довшим за тіло). Демонструє агресивне відхилення низьких цін.', visualType: 'CANDLE_HAMMER', example: 'Молот на рівні підтримки дав впевнену точку входу в лонг.' },
        { id: 'engulfing', term: 'Бичаче Поглинання', category: 'PATTERNS', definition: 'Потужна розворотна комбінація, де тіло зеленої свічки повністю перекриває тіло попередньої червоної свічки.', visualType: 'CANDLE_ENGULFING', example: 'Покупці перехопили ініціативу на ключовому рівні.' },
        { id: 'morningstar', term: 'Ранкова Зірка (Morning Star)', category: 'PATTERNS', definition: 'Трисвічкова модель розвороту на дні: довга червона свічка, свічка невизначеності з розривом і сильна зелена свічка.', visualType: 'CANDLE_MORNING_STAR', example: 'Формування на 4H таймфреймі підтвердило дно корекції.' },
        { id: 'shootingstar', term: 'Падаюча Зірка (Shooting Star)', category: 'PATTERNS', definition: 'Ведмежа свічка розвороту з маленьким нижнім тілом та довгим верхнім ґнотом, що свідчить про жорстку відсіч покупцям на максимумі.', visualType: 'CANDLE_SHOOTING_STAR', example: 'Спроба вийти на новий хай закінчилася довгим ґнотом і зливом.' },
        { id: 'cupandhandle', term: 'Чашка з Ручкою', category: 'PATTERNS', definition: 'Бичачий патерн довгострокового накопичення: плавне заокруглене дно (чашка) та невелика корекція (ручка) перед вибуховим пробоєм.', visualType: 'CHART_CUP_HANDLE', example: 'Накопичення обсягів тривало 3 місяці перед виходом на ATH.' },
        { id: 'doubletop', term: 'Подвійна Вершина ("M")', category: 'PATTERNS', definition: 'Ведмежий патерн. Ціна двічі тестує один і той самий рівень опору, не може його подолати та пробиває локальний мінімум униз.', visualType: 'CHART_DOUBLE_TOP', example: 'Невдалий штурм $70,000 сформував подвійну вершину.' },
        { id: 'doublebottom', term: 'Подвійне Дно ("W")', category: 'PATTERNS', definition: 'Бичачий розворотний патерн. Ціна двічі відштовхується від сильної зони підтримки, формуючи основу для росту.', visualType: 'CHART_DOUBLE_BOTTOM', example: 'Відскок від $60,000 сформував стійку платформу покупців.' },
        { id: 'ascendingtriangle', term: 'Висхідний Трикутник', category: 'PATTERNS', definition: 'Бичача фігура з горизонтальним рівнем опору та підвищенням локальних мінімумів, що демонструє зростаючий тиск покупців.', visualType: 'CHART_ASC_TRIANGLE', example: 'Покупці постійно підтискають ціну до опору $100.' },
        { id: 'descendingtriangle', term: 'Низхідний Трикутник', category: 'PATTERNS', definition: 'Ведмежа фігура з пласким рівнем підтримки та постійним зниженням вершин. Сигналізує про поступове продавлювання ціни вниз.', visualType: 'CHART_DESC_TRIANGLE', example: 'Підтримка слабшала з кожним ударом і врешті була пробита.' },
        { id: 'smc', term: 'Smart Money Concepts (SMC)', category: 'PATTERNS', definition: 'Торгова методологія, що відстежує дії маркетмейкерів та банків: збір ліквідності натовпу перед формуванням справжнього напрямку ціни.', visualType: 'CHART_SMC', example: 'Збір стопів роздрібних трейдерів перед потужним лонгом.' },
        { id: 'orderblock', term: 'Ордер Блок (OB)', category: 'PATTERNS', definition: 'Остання свічка перед сильним імпульсом, де великий гравець залишив незаповнені лімітні ордери. Виступає міцною магнітною зоною підтримки/опору.', visualType: 'CHART_OB', example: 'Ціна повернулася на тест бичачого OB на рівні $62,400.' },
        { id: 'fvg', term: 'Імбаланс / Розрив Ціни (FVG)', category: 'PATTERNS', definition: 'Трисвічкова цінова неефективність, де ґніт 1-ї та 3-ї свічок не торкаються один одного, утворюючи пустоту. Ціна майже завжди повертається заповнити її.', visualType: 'CHART_FVG', example: 'Вхід лімітним ордером від 50% зони FVG.' },
        { id: 'bos', term: 'BOS (Break of Structure)', category: 'PATTERNS', definition: 'Пробиття ключового екстремуму тілом свічки за напрямком тренду, що підтверджує його здорове продовження.', visualType: 'CHART_SMC', example: 'Закриття 4H свічки вище попереднього максимуму підтвердило BOS.' },
        { id: 'choch', term: 'CHoCH (Зміна Характеру Ринку)', category: 'PATTERNS', definition: 'Перше пробиття протилежного структурного рівня на молодшому таймфреймі. Ранній сигнал розвороту тренду з низхідного на висхідний.', visualType: 'CHART_SMC', example: 'CHoCH на 15m вказав на закінчення корекції старшого таймфрейму.' },
        { id: 'liquiditysweep', term: 'Збір Ліквідності (Sweep BSL/SSL)', category: 'PATTERNS', definition: 'Хибний імпульс за рівні максимуми (Equal Highs) або мінімуми для активації стоп-лоссів натовпу перед швидким розворотом у протилежний бік.', visualType: 'CHART_SMC', example: 'Зняли ліквідність азійської сесії та пішли в глибоке падіння.' },
        { id: 'breakerblock', term: 'Брейкер Блок (Breaker Block)', category: 'PATTERNS', definition: 'Пробитий ордер-блок, за яким зняли ліквідність. При поверненні ціни він дзеркально перетворюється на підтримку (або опір).', visualType: 'CHART_OB', example: 'Пробитий ведмежий блок став міцною бичачою підтримкою.' },

        // ==========================================
        // 2. ТЕХНІЧНІ ІНДИКАТОРИ ТА МЕХАНІКА РИНКУ
        // ==========================================
        { id: 'rsi', term: 'RSI (Індекс Відносної Сили)', category: 'TECHNICAL', definition: 'Осцилятор (0-100), що вимірює швидкість руху ціни. Значення >70 свідчать про перекупленість, а <30 — про локальну перепроданість активу.', example: 'Бичача дивергенція: ціна впала нижче, а RSI виріс.', visualType: 'NONE' },
        { id: 'macd', term: 'MACD (Сходження/Розходження)', category: 'TECHNICAL', definition: 'Трендовий індикатор на базі двох ковзних середніх (12 та 26). Перетин сигнальної лінії («Золотий хрест») вказує на зародження висхідного імпульсу.', example: 'Перетин ліній вище нуля дав сильний сигнал на покупку.', visualType: 'NONE' },
        { id: 'bollinger', term: 'Смуги Боллінджера', category: 'TECHNICAL', definition: 'Канали волатильності навколо 20-періодної середньої. Сильне звуження смуг (стиснення волатильності) завжди передує потужному вибуху ціни.', example: 'Стиснення смуг на 1D завершилося виходом на +20%.', visualType: 'NONE' },
        { id: 'fibonacci', term: 'Рівні Фібоначчі (Golden Pocket)', category: 'TECHNICAL', definition: 'Горизонтальні коефіцієнти золотого перетину. Зона між 0.618 та 0.65 вважається «золотим кишенею» з найвищою ймовірністю відскоку в тренді.', example: 'Ідеальний вхід у лонг від рівня корекції 0.618.', visualType: 'NONE' },
        { id: 'ema', term: 'EMA 200 & EMA 50 (Золотий / Смертельний Хрест)', category: 'TECHNICAL', definition: 'Експоненційні ковзні середні. Перетин 50 EMA вище 200 EMA — це Золотий Хрест (глобальний бичачий тренд); перетин униз — Смертельний Хрест.', example: 'Утримання ціни над 200 EMA підтверджує силу ринку.', visualType: 'NONE' },
        { id: 'volume', term: 'Профіль Об\'єму та POC (Point of Control)', category: 'TECHNICAL', definition: 'Гістограма проторгованого об\'єму за ціновими рівнями, а не часом. Рівень POC має найбільший накопичений обсяг і виступає магнітом для ціни.', example: 'Тест рівня POC на $64k спрацював як непробивна підтримка.', visualType: 'NONE' },
        { id: 'fundingrate', term: 'Funding Rate (Ставка Фінансування)', category: 'TECHNICAL', definition: 'Регулярні виплати між лонгами та шортами на безстрокових ф\'ючерсах. Високий позитивний фандінг свідчить про перегрів лонгів та ризик сквізу вниз.', example: 'Екстремально негативний фандінг викликав шорт-сквіз на $3000.', visualType: 'NONE' },
        { id: 'openinterest', term: 'Open Interest (Відкритий Інтерес)', category: 'TECHNICAL', definition: 'Загальна кількість відкритих активних контрактів на деривативах. Зростання ціни разом зі зростанням OI означає приплив свіжих грошей у тренд.', example: 'Спад ціни при падінні OI вказав на просте закриття лонгів.', visualType: 'NONE' },
        { id: 'cvd', term: 'CVD (Кумулятивна Дельта Об\'єму)', category: 'TECHNICAL', definition: 'Різниця між ринковими покупками та продажами. Дивергенція з графіком розкриває приховане лімітне поглинання великими гравцями.', example: 'Ціна стояла на місці, а CVD росла — маркетмейкер накопичував лонг.', visualType: 'NONE' },
        { id: 'liqheatmap', term: 'Карта Ліквідацій (Heatmap)', category: 'TECHNICAL', definition: 'Візуальна карта цінових рівнів, де скупчені примусові ліквідації позицій натовпу з великим плечем. Ціна рухається до них як до джерела палива.', example: 'Ціна шпилькою зняла ліквідації на $68k і різко розвернулася.', visualType: 'NONE' },
        { id: 'orderbookdepth', term: 'Стакан Ордерів та Спуфінг (Spoofing)', category: 'TECHNICAL', definition: 'Глибина лімітних заявок (Bid/Ask). Спуфінг — це маніпуляція, коли боти ставлять величезну стіну, щоб налякати ринок, і знімають її перед виконанням.', example: 'Фальшиву стінку на 500 BTC прибрали перед самим підходом ціни.', visualType: 'NONE' },

        // ==========================================
        // 3. ПСИХОЛОГІЯ, МЕНЕДЖМЕНТ РИЗИКУ ТА КАПІТАЛ
        // ==========================================
        { id: 'riskreward', term: 'Співвідношення Ризик/Прибуток (R:R)', category: 'PSYCHOLOGY', definition: 'Математичне співвідношення потенційного збитку до профіту. За умови RR 1:3 ви можете помилятися у 60% угод і все одно стабільно збільшувати депозит.', example: 'Ризикуємо $100 заради цілі в $300 (R:R 1:3).', visualType: 'NONE' },
        { id: 'onepercentrule', term: 'Правило 1% Ризику на Угоду', category: 'PSYCHOLOGY', definition: 'Золоте правило професіоналів: максимальний ризик у разі спрацювання стоп-лоссу не повинен перевищувати 1-2% від загального розміру вашого депозиту.', example: 'Депозит $10,000 — максимальний стоп $100 на угоду.', visualType: 'NONE' },
        { id: 'fomo', term: 'FOMO (Страх Втраченої Вигоди)', category: 'PSYCHOLOGY', definition: 'Непереборне бажання купити монету, яка вже дала шалений ріст, через заздрість та страх упустити легкі гроші. Головна причина зливів новачків.', example: 'Купівля мемкоїна на піку після трьох зелених свічок.', visualType: 'NONE' },
        { id: 'fud', term: 'FUD (Страх, Невизначеність, Сумнів)', category: 'PSYCHOLOGY', definition: 'Поширення дезінформації або тривожних новин у ЗМІ з метою викликати панічні продажі у натовпу, щоб великі фонди могли відкупити дно.', example: 'Панічний продаж на новинах про заборону, після чого ринок полетів вгору.', visualType: 'NONE' },
        { id: 'revengetrading', term: 'Торгівля з Помсти (Тильт)', category: 'PSYCHOLOGY', definition: 'Спроба миттєво відіграти втрачений збиток, відкриваючи несистемні угоди з гігантським плечем. Найшвидший шлях до повної ліквідації рахунку.', example: 'Отримав стоп на $50 і залетів у 50х плече всією котлетою.', visualType: 'NONE' },
        { id: 'dca', term: 'DCA (Усереднення Доларової Вартості)', category: 'PSYCHOLOGY', definition: 'Стратегія інвестування фіксованої суми грошей через регулярні проміжки часу незалежно від ціни. Знімає стрес від спроб зловити дно.', example: 'Купівля BTC на $50 кожного понеділка незалежно від новин.', visualType: 'NONE' },
        { id: 'diamondhands', term: 'Діамантові та Паперові Руки', category: 'PSYCHOLOGY', definition: '«Діамантові руки» — здатність тримати перспективні активи під час жорстких просадок; «Паперові руки» продають на першій же червоній свічці.', example: 'Холдив спотові позиції під час 30% ринкового падіння.', visualType: 'NONE' },
        { id: 'biasconfirmation', term: 'Упередження Підтвердження та Тильт', category: 'PSYCHOLOGY', definition: 'Психологічна пастка, коли трейдер шукає в інтернеті лише думки на користь своєї збиткової позиції та відмовляється закрити помилкову угоду.', example: 'Шукав пости аналітиків про туземун, коли ціна вже пробила стоп.', visualType: 'NONE' },

        // ==========================================
        // 4. БЕЗПЕКА, ЗАХИСТ ВІД ШАХРАЇВ ТА СМАРТ-КОНТРАКТИ
        // ==========================================
        { id: 'seed', term: 'Сід-фраза (Secret Recovery Phrase)', category: 'SECURITY', definition: 'Секретна комбінація з 12 або 24 слів, яка є єдиним майстер-ключем до всього вашого гаманця. Будь-хто, хто дізнається її, отримує повний контроль над коштами.', example: 'Зберігайте офлайн на металевій пластині; ніколи не вводьте на сайтах.', visualType: 'NONE' },
        { id: '2fa', term: '2FA (Двофакторна Аутентифікація)', category: 'SECURITY', definition: 'Другий рівень захисту облікового запису. Використовуйте апаратні ключі або застосунки Google/Apple Authenticator, але ніколи не SMS-код (ризик SIM-swap).', example: 'Захистив біржовий акаунт через ключ YubiKey.', visualType: 'NONE' },
        { id: 'coldstorage', term: 'Холодне Зберігання (Апаратні Гаманці)', category: 'SECURITY', definition: 'Фізичні пристрої (Ledger, Trezor, Keystone), які зберігають ваші приватні ключі в ізольованому чіпі без підключення до інтернету.', example: 'Тримаю 90% довгострокового криптокапіталу на холодному гаманці.', visualType: 'NONE' },
        { id: 'drainers', term: 'Дрейнери та Дозволи (Permit Scams)', category: 'SECURITY', definition: 'Шахрайські скрипти, що виманюють підпис дозволу транзакції без сплати газу (Permit). Один неперевірений підпис дозволяє злодіям спустошити ваш баланс.', example: 'Регулярно відкликайте старі дозволи через сервіс revoke.cash.', visualType: 'NONE' },
        { id: 'addresspoisoning', term: 'Отруєння Адреси (Address Poisoning)', category: 'SECURITY', definition: 'Шахраї створюють адресу з першими та останніми символами, ідентичними вашій, і надсилають 0 монет. Якщо ви скопіюєте адресу з історії — надішлете гроші скамеру.', example: 'Завжди перевіряйте всі символи адреси, а не копіюйте з історії.', visualType: 'NONE' },
        { id: 'honeypot', term: 'Honeypot та 100% Tax Токени', category: 'SECURITY', definition: 'Підступні смарт-контракти нових щиткоїнів, які дозволяють купити токен, але блокують функцію sell() або ставлять 100% комісію на продаж.', example: 'Перед покупкою перевірив контракт на сервісі Honeypot.is.', visualType: 'NONE' },
        { id: 'slippage', term: 'Slippage (Проковзування) та MEV-боти', category: 'SECURITY', definition: 'Допустима різниця між очікуваною ціною та ціною виконання на DEX. Високий slippage (>2%) дозволяє MEV-ботам здійснити «сендвіч-атаку» на ваш обмін.', example: 'Виставив точний slippage 0.5% і захистився від MEV-ботів.', visualType: 'NONE' },
        { id: 'fdv', term: 'Капіталізація vs FDV (Розбавлена Вартість)', category: 'SECURITY', definition: 'Market Cap — вартість монет в обігу. FDV — вартість усіх монет, які коли-небудь будуть випущені. Величезний FDV означає постійний тиск розблокувань фондів.', example: 'Капіталізація $100M, а FDV $5B — токен знецінився через анлоки інвесторів.', visualType: 'NONE' },
        { id: 'smartcontract', term: 'Аудит Смарт-контрактів та Адмін-ключі', category: 'SECURITY', definition: 'Приховані функції в коді (можливість друкувати необмежену кількість монет, зупиняти торги або змінювати логіку без голосування DAO).', example: 'У контракті залишилася відкрита функція mint() для розробника.', visualType: 'NONE' },
    ],

    pl: [
        // ==========================================
        // 1. FORMACJE ŚWIECOWE, WYKRESY I SMC
        // ==========================================
        { id: 'hns', term: 'Głowa i Ramiona (RGR)', category: 'PATTERNS', definition: 'Klasyczna formacja odwrócenia z trzema szczytami. Przebicie linii szyi w dół potwierdza zmianę trendu ze wzrostowego na spadkowy.', visualType: 'CHART_HEAD_SHOULDERS', example: 'Cena nie zdołała wybić szczytu i przebiła linię szyi na $65k.' },
        { id: 'bullflag', term: 'Flaga Byka (Bull Flag)', category: 'PATTERNS', definition: 'Formacja kontynuacji trendu wzrostowego. Gwałtowny impuls w górę (maszt) i wąska konsolidacja w dół (flaga).', visualType: 'CHART_BULL_FLAG', example: 'Konsolidacja po wzroście +15% zakończona wybiciem w górę.' },
        { id: 'fallingwedge', term: 'Klin Zniżkujący', category: 'PATTERNS', definition: 'Formacja byka. Cena zacieśnia się w dół między zbiegającymi się liniami, zwiastując wyczerpanie podaży i nagły wystrzał w górę.', visualType: 'CHART_WEDGE_BULL', example: 'Bycza dywergencja na klinie doprowadziła do wybicia.' },
        { id: 'risingwedge', term: 'Klin Zwyżkujący', category: 'PATTERNS', definition: 'Formacja niedźwiedzia. Cena rośnie, ale zakres ruchów zacieśnia się przy spadającym wolumenie, co zapowiada mocny spadek.', visualType: 'CHART_WEDGE_BEAR', example: 'Wyczerpanie wolumenu w klinie skutkowało załamaniem wsparcia.' },
        { id: 'doji', term: 'Świeca Doji', category: 'PATTERNS', definition: 'Świeca, w której cena otwarcia i zamknięcia są prawie równe. Wskazuje na całkowitą równowagę i niezdecydowanie rynku.', visualType: 'CANDLE_DOJI', example: 'Doji na szczycie dziennego wykresu ostrzega przed korektą.' },
        { id: 'hammer', term: 'Młot Byczy (Hammer)', category: 'PATTERNS', definition: 'Świeca odwrócenia z małym korpusem u góry i długim dolnym knotem (minimum 2x długości korpusu), odrzucająca niższe ceny.', visualType: 'CANDLE_HAMMER', example: 'Odbicie na poziomie wsparcia dało świetny punkt wejścia.' },
        { id: 'engulfing', term: 'Objęcie Bycze (Engulfing)', category: 'PATTERNS', definition: 'Silna formacja odwrócenia, w której duża zielona świeca całkowicie pochłania korpus poprzedniej czerwonej świecy.', visualType: 'CANDLE_ENGULFING', example: 'Kupujący przejęli kontrolę na dołku wyprzedaży.' },
        { id: 'morningstar', term: 'Gwiazda Poranna (Morning Star)', category: 'PATTERNS', definition: 'Trzyświecowa formacja odwrócenia na dnie: długa czerwona świeca, świeca niezdecydowania z luką i silna zielona świeca.', visualType: 'CANDLE_MORNING_STAR', example: 'Potwierdzenie zakończenia korekty na interwale 4H.' },
        { id: 'shootingstar', term: 'Spadająca Gwiazda (Shooting Star)', category: 'PATTERNS', definition: 'Świeca niedźwiedzia z małym dolnym korpusem i długim górnym knotem, pokazująca agresywne odrzucenie na szczycie.', visualType: 'CANDLE_SHOOTING_STAR', example: 'Próba nowego szczytu zakończyła się knotem i zrzutem.' },
        { id: 'cupandhandle', term: 'Filiżanka z Uchem', category: 'PATTERNS', definition: 'Bycza formacja długoterminowej akumulacji: zaokrąglone dno (filiżanka) i łagodna korekta (ucho) przed silnym wybiciem.', visualType: 'CHART_CUP_HANDLE', example: 'Długoterminowa baza przed atakiem na nowe ATH.' },
        { id: 'doubletop', term: 'Podwójny Szczyt ("M")', category: 'PATTERNS', definition: 'Formacja odwrócenia w dół. Cena dwukrotnie uderza w ten sam opór, nie może go przebić i spada poniżej dołka.', visualType: 'CHART_DOUBLE_TOP', example: 'Dwukrotne odrzucenie z poziomu $70,000.' },
        { id: 'doublebottom', term: 'Podwójne Dno ("W")', category: 'PATTERNS', definition: 'Formacja odwrócenia w górę. Cena dwukrotnie broni strefy wsparcia, tworząc solidną podstawę pod rajd cenowy.', visualType: 'CHART_DOUBLE_BOTTOM', example: 'Podwójne odbicie od wsparcia na poziomie $60,000.' },
        { id: 'ascendingtriangle', term: 'Trójkąt Zwyżkujący', category: 'PATTERNS', definition: 'Formacja byka z płaskim oporem i coraz wyższymi dołkami, pokazująca rosnącą presję kupujących przed wybiciem.', visualType: 'CHART_ASC_TRIANGLE', example: 'Cena dociskana do oporu $100 aż do wybicia.' },
        { id: 'descendingtriangle', term: 'Trójkąt Zniżkujący', category: 'PATTERNS', definition: 'Formacja niedźwiedzia z płaskim wsparciem i coraz niższymi szczytami. Oznacza stopniowe wyczerpywanie popytu.', visualType: 'CHART_DESC_TRIANGLE', example: 'Wsparcie osłabione kolejnymi testami pękło.' },
        { id: 'smc', term: 'Smart Money Concepts (SMC)', category: 'PATTERNS', definition: 'Metodologia śledząca zlecenia instytucji i banków: polowanie na płynność detalistów przed wykonaniem właściwego ruchu.', visualType: 'CHART_SMC', example: 'Zgarnięcie stop-lossów przed właściwym rajdem cenowym.' },
        { id: 'orderblock', term: 'Blok Zleceń (Order Block / OB)', category: 'PATTERNS', definition: 'Ostatnia przeciwna świeca przed impulsem wybiciowym, w której instytucje pozostawiły niewypełnione zlecenia oczekujące.', visualType: 'CHART_OB', example: 'Cena przetestowała byczy blok zleceń na poziomie $62,400.' },
        { id: 'fvg', term: 'Luka Płynności (Fair Value Gap / FVG)', category: 'PATTERNS', definition: 'Nierównowaga cenowa między knotem świecy 1 i 3, pozostawiająca pustą przestrzeń, którą rynek z reguły wypełnia.', visualType: 'CHART_FVG', example: 'Wejście z limitu na poziomie 50% FVG.' },
        { id: 'bos', term: 'BOS (Przełamanie Struktury)', category: 'PATTERNS', definition: 'Zamknięcie korpusu świecy ponad ostatnim szczytem (w trendzie wzrostowym) potwierdzające kontynuację trendu.', visualType: 'CHART_SMC', example: 'Świeca 4H zamknęła się powyżej szczytu tworząc BOS.' },
        { id: 'choch', term: 'CHoCH (Zmiana Charakteru Rynku)', category: 'PATTERNS', definition: 'Pierwsze wybicie przeciwnego punktu strukturalnego sygnalizujące wczesne odwrócenie trendu ze spadkowego na wzrostowy.', visualType: 'CHART_SMC', example: 'CHoCH na interwale 15m dał wczesny sygnał zakończenia korekty.' },
        { id: 'liquiditysweep', term: 'Czyszczenie Płynności (Liquidity Sweep)', category: 'PATTERNS', definition: 'Szybkie wybicie knotem ponad równe szczyty lub pod dołki w celu aktywacji zleceń stop loss przed natychmiastowym zwrotem.', visualType: 'CHART_SMC', example: 'Zdjęcie płynności sesji azjatyckiej i dynamiczny spadek.' },
        { id: 'breakerblock', term: 'Breaker Block', category: 'PATTERNS', definition: 'Przebity Order Block, który po zdjęciu płynności staje się strefą wsparcia lub oporu przy powrocie ceny.', visualType: 'CHART_OB', example: 'Przebity blok niedźwiedzi działa teraz jako wsparcie.' },

        // ==========================================
        // 2. WSKAŹNIKI TECHNICZNE I MECHANIKA RYNKU
        // ==========================================
        { id: 'rsi', term: 'RSI (Indeks Siły Względnej)', category: 'TECHNICAL', definition: 'Wskaźnik momentum (0-100). Wartości powyżej 70 oznaczają wykupienie rynku, a poniżej 30 wyprzedanie.', example: 'Bycza dywergencja: cena spada, a RSI rośnie.', visualType: 'NONE' },
        { id: 'macd', term: 'MACD (Zbieżność i Rozbieżność)', category: 'TECHNICAL', definition: 'Wskaźnik podążający za trendem na bazie dwóch średnich EMA. Przecięcie linii sygnałowej w górę sugeruje wejście w pozycję.', example: 'Złoty Krzyż MACD powyżej zera potwierdził hossę.', visualType: 'NONE' },
        { id: 'bollinger', term: 'Wstęgi Bollingera', category: 'TECHNICAL', definition: 'Wstęgi zmienności wokół 20-okresowej średniej SMA. Zaciśnięcie wstęg zwiastuje gwałtowny wybuch zmienności.', example: 'Ściśnięcie wstęg zakończyło się rajdem o 25%.', visualType: 'NONE' },
        { id: 'fibonacci', term: 'Poziomy Fibonacciego (Golden Pocket)', category: 'TECHNICAL', definition: 'Poziome zniesienia matematyczne. Strefa 0.618 - 0.65 to tzw. Złota Kieszeń o najwyższym prawdopodobieństwie odbicia w trendzie.', example: 'Idealne wejście w pozycję na zniesieniu 0.618.', visualType: 'NONE' },
        { id: 'ema', term: 'Średnie EMA 200 i EMA 50', category: 'TECHNICAL', definition: 'Wykładnicze średnie kroczące. Przecięcie EMA 50 ponad EMA 200 to Złoty Krzyż (hossa); przecięcie w dół to Krzyż Śmierci (bessa).', example: 'Utrzymanie ceny powyżej 200 EMA świadczy o sile rynku.', visualType: 'NONE' },
        { id: 'volume', term: 'Profil Wolumenu i Poziom POC', category: 'TECHNICAL', definition: 'Rozkład wolumenu według poziomów cenowych. POC (Point of Control) to poziom o najwyższym obrocie, działający jak magnes na cenę.', example: 'Test poziomu POC na cenie $64k zadziałał jako silne wsparcie.', visualType: 'NONE' },
        { id: 'fundingrate', term: 'Funding Rate (Stopa Finansowania)', category: 'TECHNICAL', definition: 'Płatności między pozycjami long i short na kontraktach perpetual. Bardzo wysoki funding oznacza przegrzanie rynku i ryzyko zrzutu.', example: 'Ekstremalnie ujemny funding wywołał short squeeze.', visualType: 'NONE' },
        { id: 'openinterest', term: 'Open Interest (Otwarte Pozycje)', category: 'TECHNICAL', definition: 'Łączna liczba aktywnych kontraktów na rynku instrumentów pochodnych. Wzrost ceny wraz ze wzrostem OI potwierdza napływ nowego kapitału.', example: 'Spadek ceny przy spadku OI oznaczał jedynie likwidację longów.', visualType: 'NONE' },
        { id: 'cvd', term: 'CVD (Skumulowana Delta Wolumenu)', category: 'TECHNICAL', definition: 'Różnica między rynkowym wolumenem kupna a sprzedaży. Dywergencja z ceną ujawnia ukrytą absorpcję zleceniami limit.', example: 'CVD rosło podczas gdy cena stała w miejscu — akumulacja instytucji.', visualType: 'NONE' },
        { id: 'liqheatmap', term: 'Mapa Likwidacji (Liquidation Heatmap)', category: 'TECHNICAL', definition: 'Wizualna mapa stref, w których skoncentrowane są likwidacje pozycji z dużą dźwignią. Cena zachowuje się jak magnes dążąc do tych poziomów.', example: 'Cena knotem zebrała pulę likwidacji na $68k i natychmiast spadła.', visualType: 'NONE' },
        { id: 'orderbookdepth', term: 'Głębokość Księgi Zleceń i Spoofing', category: 'TECHNICAL', definition: 'Zestawienie zleceń kupna i sprzedaży. Spoofing to manipulacja polegająca na stawianiu fałszywych ścian zleceń i kasowaniu ich przed realizacją.', example: 'Fałszywa ściana 500 BTC została wycofana tuż przed dojściem ceny.', visualType: 'NONE' },

        // ==========================================
        // 3. PSYCHOLOGIA, ZARZĄDZANIE RYZYKIEM I KAPITAŁEM
        // ==========================================
        { id: 'riskreward', term: 'Stosunek Zysku do Ryzyka (Risk/Reward)', category: 'PSYCHOLOGY', definition: 'Matematyczny stosunek potencjalnej straty do zysku. Przy R:R 1:3 możesz mylić się w 60% zagrań i nadal osiągać stabilny zysk.', example: 'Ryzykujesz $100, aby zarobić $300 (setup 1:3 R:R).', visualType: 'NONE' },
        { id: 'onepercentrule', term: 'Zasada 1% Ryzyka na Transakcję', category: 'PSYCHOLOGY', definition: 'Złota reguła tradingu: maksymalna strata przy uderzeniu w Stop Loss nie może przekraczać 1-2% całego kapitału na rachunku.', example: 'Rachunek $10,000 — strata maksymalna $100 na jedną pozycję.', visualType: 'NONE' },
        { id: 'fomo', term: 'FOMO (Strach Przed Pominięciem)', category: 'PSYCHOLOGY', definition: 'Emocjonalny impuls kupowania aktywa, które już mocno wzrosło, wywołany chciwością. Główna przyczyna strat początkujących inwestorów.', example: 'Kupowanie memecoina po wzroście o 300% na zielonej świecy.', visualType: 'NONE' },
        { id: 'fud', term: 'FUD (Strach, Niepewność, Wątpliwość)', category: 'PSYCHOLOGY', definition: 'Celowe szerzenie negatywnych lub fałszywych informacji w celu wywołania paniki i odkupienia aktywów taniej przez wielkich graczy.', example: 'Sprzedaż w panice po nagłówkach o zakazie krypto.', visualType: 'NONE' },
        { id: 'revengetrading', term: 'Revenge Trading (Trading w Tilcie)', category: 'PSYCHOLOGY', definition: 'Próba natychmiastowego odrobienia straty poprzez otwarcie nieprzemyślanych pozycji z maksymalną dźwignią. Najkrótsza droga do wyzerowania konta.', example: 'Otrzymał stopa i wszedł całą kwotą z dźwignią 50x.', visualType: 'NONE' },
        { id: 'dca', term: 'DCA (Uśrednianie Kosztu w Dolarach)', category: 'PSYCHOLOGY', definition: 'Strategia regularnego zakupu za stałą kwotę w stałych odstępach czasu niezależnie od ceny, eliminująca stres emocjonalny.', example: 'Inwestowanie $50 w BTC w każdy poniedziałek.', visualType: 'NONE' },
        { id: 'diamondhands', term: 'Diamentowe vs Papierowe Ręce', category: 'PSYCHOLOGY', definition: '"Diamentowe Ręce" utrzymują pozycje wbrew dużej zmienności; "Papierowe Ręce" panicznie sprzedają przy pierwszym spadku.', example: 'Trzymanie pozycji spotowych mimo korekty o 30%.', visualType: 'NONE' },
        { id: 'biasconfirmation', term: 'Błąd Konfirmacji i Utracone Koszty', category: 'PSYCHOLOGY', definition: 'Szukanie w sieci wyłącznie opinii potwierdzających Twoją stratną pozycję zamiast zaakceptowania technicznego wybicia stop lossa.', example: 'Szukanie optymistycznych postów gdy wykres zanegował setup.', visualType: 'NONE' },

        // ==========================================
        // 4. BEZPIECZEŃSTWO, OCHRONA PRZED OSZUSTWAMI I SMART CONTRACTS
        // ==========================================
        { id: 'seed', term: 'Fraza Seed (Secret Recovery Phrase)', category: 'SECURITY', definition: 'Sekwencja 12 lub 24 słów stanowiąca klucz główny do Twojego portfela. Każdy, kto ją pozna, przejmuje całkowitą kontrolę nad Twoimi środkami.', example: 'Zapisz offline na stali; NIGDY nie wpisuj na stronach internetowych.', visualType: 'NONE' },
        { id: '2fa', term: '2FA (Uwierzytelnianie Dwuskładnikowe)', category: 'SECURITY', definition: 'Druga warstwa ochrony konta. Używaj kluczy YubiKey lub aplikacji uwierzytelniających (Google Authenticator), unikaj kodów SMS (ryzyko SIM-swap).', example: 'Zabezpieczenie konta giełdowego kluczem sprzętowym.', visualType: 'NONE' },
        { id: 'coldstorage', term: 'Zimny Portfel (Hardware Wallet)', category: 'SECURITY', definition: 'Dedykowane urządzenia fizyczne (Ledger, Trezor, Keystone) przechowujące klucze prywatne w odizolowanym środowisku offline.', example: '90% długoterminowego kapitału trzymane na zimnym portfelu.', visualType: 'NONE' },
        { id: 'drainers', term: 'Drainery i Podpisy Pozwoleń (Permit Scams)', category: 'SECURITY', definition: 'Złośliwe skrypty wyłudzające podpisy transakcji (Permit/Approval). Jeden nieostrożny podpis daje oszustom prawo do wyczyszczenia portfela.', example: 'Regularne cofanie starych uprawnień na revoke.cash.', visualType: 'NONE' },
        { id: 'addresspoisoning', term: 'Address Poisoning (Zatruwanie Adresów)', category: 'SECURITY', definition: 'Oszuści tworzą adres z identycznymi pierwszymi i ostatnimi znakami co Twój i wysyłają 0 monet, licząc że skopiujesz adres z historii.', example: 'Zawsze weryfikuj cały ciąg znaków adresu, nie kopiuj z historii.', visualType: 'NONE' },
        { id: 'honeypot', term: 'Honeypot i Tokeny ze 100% Podatkiem', category: 'SECURITY', definition: 'Oszukańczy smart contract pozwalający na zakup tokena, lecz blokujący funkcję sprzedaży sell() lub nakładający 100% podatku.', example: 'Sprawdzenie kontraktu na Honeypot.is przed zakupem.', visualType: 'NONE' },
        { id: 'slippage', term: 'Slippage (Poślizg Cenowy) i Boty MEV', category: 'SECURITY', definition: 'Dopuszczalna różnica między ceną oczekiwaną a zrealizowaną na DEX. Zbyt wysoki poślizg (>2%) naraża Cię na atak typu sandwich ze strony botów MEV.', example: 'Ustawienie poślizgu na 0.5% ochroniło transakcję przed botem MEV.', visualType: 'NONE' },
        { id: 'fdv', term: 'Kapitalizacja vs FDV (Pełne Rozwodnienie)', category: 'SECURITY', definition: 'Market Cap to wartość monet w obiegu. FDV to wartość po wyemitowaniu całej podaży. Gigantyczne FDV oznacza brutalną presję zrzutu z unlocków.', example: 'Kapitalizacja $100M przy FDV $5B doprowadziła do spadku o 80%.', visualType: 'NONE' },
        { id: 'smartcontract', term: 'Audyt Smart Contractu i Uprawnienia Admina', category: 'SECURITY', definition: 'Ukryte luki w kodzie lub scentralizowane uprawnienia (możliwość nieograniczonego bicia monet mint() lub blokowania transferów).', example: 'Twórca tokena zachował funkcję mint() umożliwiającą zrzut.', visualType: 'NONE' },
    ]
};
