import React, { useState } from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { ShieldIcon, ChevronRightIcon, CheckIcon } from './icons';
import { triggerHaptic } from '../utils/haptics';

const TwoFactorAuthModal: React.FC<{ onClose: () => void }> = ({ onClose }) => {
    const [step, setStep] = useState<'INTRO' | 'QR' | 'VERIFY' | 'SUCCESS'>('INTRO');
    const [code, setCode] = useState('');
    const [error, setError] = useState('');

    // Mock secret for UI purposes
    const secret = "JBSWY3DPEHPK3PXP";
    const qrUrl = `otpauth://totp/StorkCrypto:User?secret=${secret}&issuer=StorkCrypto`;

    const handleVerify = () => {
        if (code.length === 6 && /^\d+$/.test(code)) {
            triggerHaptic('success');
            setStep('SUCCESS');
        } else {
            triggerHaptic('error');
            setError('Invalid code. Must be 6 digits.');
        }
    };

    return (
        <div className="fixed inset-0 z-[150] bg-brand-bg/95 backdrop-blur-3xl flex flex-col animate-fade-in">
            <div className="safe-area-pt px-6 py-5 flex items-center justify-between border-b border-white/10">
                <button onClick={() => { triggerHaptic('light'); onClose(); }} className="w-10 h-10 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center text-slate-300 active:scale-90 transition-all">
                    <ChevronRightIcon className="w-6 h-6 rotate-180" />
                </button>
                <h2 className="font-orbitron text-sm font-black text-white tracking-widest uppercase">2FA Setup</h2>
                <div className="w-10"></div>
            </div>

            <div className="flex-1 overflow-y-auto p-6 flex flex-col items-center justify-center text-center">
                {step === 'INTRO' && (
                    <div className="max-w-xs animate-slide-up">
                        <div className="w-20 h-20 rounded-full bg-brand-purple/20 border-2 border-brand-purple/40 flex items-center justify-center mx-auto mb-6 shadow-[0_0_30px_rgba(189,0,255,0.3)]">
                            <ShieldIcon className="w-10 h-10 text-brand-purple" />
                        </div>
                        <h3 className="text-xl font-black text-white font-orbitron uppercase mb-3">Secure Your Account</h3>
                        <p className="text-xs text-slate-400 font-mono mb-8">Enable Two-Factor Authentication (2FA) to add an extra layer of security to your Neural Terminal.</p>
                        <button 
                            onClick={() => { triggerHaptic('medium'); setStep('QR'); }}
                            className="w-full py-4 bg-brand-purple text-white font-black font-orbitron uppercase tracking-widest rounded-2xl shadow-[0_0_20px_rgba(189,0,255,0.4)] active:scale-95 transition-all"
                        >
                            Begin Setup
                        </button>
                    </div>
                )}

                {step === 'QR' && (
                    <div className="max-w-xs animate-slide-up w-full">
                        <h3 className="text-sm font-black text-white font-orbitron uppercase mb-2">Scan QR Code</h3>
                        <p className="text-[10px] text-slate-400 font-mono mb-6">Use Google Authenticator or Authy to scan this code.</p>
                        
                        <div className="bg-white p-4 rounded-2xl inline-block mb-6 shadow-[0_0_40px_rgba(0,240,255,0.2)]">
                            <QRCodeSVG value={qrUrl} size={200} level="H" />
                        </div>

                        <div className="bg-black/40 border border-white/10 rounded-xl p-4 mb-8">
                            <p className="text-[8px] text-slate-500 font-black uppercase tracking-widest mb-1">Manual Entry Code</p>
                            <p className="text-sm font-mono text-brand-cyan font-bold tracking-widest">{secret}</p>
                        </div>

                        <button 
                            onClick={() => { triggerHaptic('medium'); setStep('VERIFY'); }}
                            className="w-full py-4 bg-brand-cyan text-black font-black font-orbitron uppercase tracking-widest rounded-2xl shadow-[0_0_20px_rgba(0,240,255,0.4)] active:scale-95 transition-all"
                        >
                            Next Step
                        </button>
                    </div>
                )}

                {step === 'VERIFY' && (
                    <div className="max-w-xs animate-slide-up w-full">
                        <h3 className="text-sm font-black text-white font-orbitron uppercase mb-2">Verify Code</h3>
                        <p className="text-[10px] text-slate-400 font-mono mb-8">Enter the 6-digit code generated by your authenticator app.</p>
                        
                        <input 
                            type="text" 
                            maxLength={6}
                            value={code}
                            onChange={(e) => { setCode(e.target.value.replace(/\D/g, '')); setError(''); }}
                            placeholder="000000"
                            className="w-full bg-black/50 border-2 border-brand-cyan/30 rounded-2xl p-4 text-center text-3xl font-mono text-white tracking-[0.5em] focus:border-brand-cyan focus:outline-none transition-colors mb-4"
                        />
                        
                        {error && <p className="text-[10px] text-red-500 font-mono mb-4">{error}</p>}

                        <button 
                            onClick={handleVerify}
                            disabled={code.length !== 6}
                            className={`w-full py-4 font-black font-orbitron uppercase tracking-widest rounded-2xl transition-all ${code.length === 6 ? 'bg-brand-green text-black shadow-[0_0_20px_rgba(0,255,157,0.4)] active:scale-95' : 'bg-slate-800 text-slate-500'}`}
                        >
                            Verify & Enable
                        </button>
                    </div>
                )}

                {step === 'SUCCESS' && (
                    <div className="max-w-xs animate-slide-up">
                        <div className="w-20 h-20 rounded-full bg-brand-green/20 border-2 border-brand-green/40 flex items-center justify-center mx-auto mb-6 shadow-[0_0_30px_rgba(0,255,157,0.3)]">
                            <CheckIcon className="w-10 h-10 text-brand-green" />
                        </div>
                        <h3 className="text-xl font-black text-white font-orbitron uppercase mb-3">2FA Enabled</h3>
                        <p className="text-xs text-slate-400 font-mono mb-8">Your Neural Terminal is now protected with Two-Factor Authentication.</p>
                        <button 
                            onClick={() => { triggerHaptic('success'); onClose(); }}
                            className="w-full py-4 bg-white/10 text-white border border-white/20 font-black font-orbitron uppercase tracking-widest rounded-2xl active:scale-95 transition-all hover:bg-white/20"
                        >
                            Return to Profile
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};

export default TwoFactorAuthModal;
